export const productData = [
  {
    id: 1,
    category: "7 CM SPARKLERS",
    name: "7 cm Electric Sparklers",
    rate: 24,
    per: "Box (10 Pcs)",
  },
  {
    id: 2,
    category: "7 CM SPARKLERS",
    name: "7 cm Crackling Sparklers",
    rate: 32,
    per: "Box (10 Pcs)",
  },
  {
    id: 3,
    category: "7 CM SPARKLERS",
    name: "7 cm Green Sparklers",
    rate: 36,
    per: "Box (10 Pcs)",
  },
  {
    id: 4,
    category: "7 CM SPARKLERS",
    name: "7 cm Red Sparklers",
    rate: 40,
    per: "Box (10 Pcs)",
  },
  {
    id: 5,
    category: "10 CM SPARKLERS",
    name: "10 cm Electric Sparklers",
    rate: 40,
    per: "Box (10 Pcs)",
  },
  {
    id: 6,
    category: "10 CM SPARKLERS",
    name: "10 cm Crackling Sparklers",
    rate: 50,
    per: "Box (10 Pcs)",
  },
  {
    id: 7,
    category: "10 CM SPARKLERS",
    name: "10 cm Green Sparklers",
    rate: 60,
    per: "Box (10 Pcs)",
  },
  {
    id: 8,
    category: "10 CM SPARKLERS",
    name: "10 cm Red Sparklers",
    rate: 65,
    per: "Box (10 Pcs)",
  },
  {
    id: 9,
    category: "15 CM SPARKLERS",
    name: "15 cm Electric Sparklers",
    rate: 100,
    per: "Box (10 Pcs)",
  },
  {
    id: 10,
    category: "15 CM SPARKLERS",
    name: "15 cm Crackling Sparklers",
    rate: 120,
    per: "Box (10 Pcs)",
  },
  {
    id: 11,
    category: "15 CM SPARKLERS",
    name: "15 cm Green Sparklers",
    rate: 140,
    per: "Box (10 Pcs)",
  },
  {
    id: 12,
    category: "15 CM SPARKLERS",
    name: "15 cm Red Sparklers",
    rate: 155,
    per: "Box (10 Pcs)",
  },
  {
    id: 13,
    category: "30 CM SPARKLERS",
    name: "30 cm Electric Sparklers",
    rate: 100,
    per: "Box (5 Pcs)",
  },
  {
    id: 14,
    category: "30 CM SPARKLERS",
    name: "30 cm Crackling Sparklers",
    rate: 120,
    per: "Box (5 Pcs)",
  },
  {
    id: 15,
    category: "30 CM SPARKLERS",
    name: "30 cm Green Sparklers",
    rate: 140,
    per: "Box (5 Pcs)",
  },
  {
    id: 16,
    category: "30 CM SPARKLERS",
    name: "30 cm Red Sparklers",
    rate: 155,
    per: "Box (5 Pcs)",
  },
  {
    id: 17,
    category: "50 CM SPARKLERS",
    name: "50 cm Electric Sparklers",
    rate: 450,
    per: "Box (5 Pcs)",
  },
  {
    id: 18,
    category: "50 CM SPARKLERS",
    name: "50 cm Colour Sparklers",
    rate: 500,
    per: "Box (5 Pcs)",
  },
  {
    id: 19,
    category: "50 CM SPARKLERS",
    name: "Golden Rotating Umbrella",
    rate: 500,
    per: "Box (1 Pcs)",
  },
  {
    id: 20,
    category: "HAND TWINKLING STARS",
    name: "1.2'' Twinkling Star",
    rate: 70,
    per: "Box (10 Pcs)",
  },
  {
    id: 21,
    category: "HAND TWINKLING STARS",
    name: "4'' Twinkling Star",
    rate: 180,
    per: "Box (10 Pcs)",
  },
  {
    id: 22,
    category: "PREMIUM HAND LIGHTING STARS PENCIL",
    name: "Lamba Lamba",
    rate: 800,
    per: "Box (2 Pcs)",
  },
  {
    id: 23,
    category: "PREMIUM HAND LIGHTING STARS PENCIL",
    name: "Candy Crush Pencil",
    rate: 240,
    per: "Box (3 Pcs)",
  },
  {
    id: 24,
    category: "PREMIUM HAND LIGHTING STARS PENCIL",
    name: "Laser Drops Pencil",
    rate: 360,
    per: "Box (3 Pcs)",
  },
  {
    id: 25,
    category: "FLORAL FLOWER POTS",
    name: "Flower Pot Small",
    rate: 130,
    per: "Box (10 Pcs)",
  },
  {
    id: 26,
    category: "FLORAL FLOWER POTS",
    name: "Flower Pot Big",
    rate: 200,
    per: "Box (10 Pcs)",
  },
  {
    id: 27,
    category: "FLORAL FLOWER POTS",
    name: "Flower Pot Special",
    rate: 250,
    per: "Box (10 Pcs)",
  },
  {
    id: 28,
    category: "FLORAL FLOWER POTS",
    name: "Flower Pot Asoka Grand",
    rate: 280,
    per: "Box (10 Pcs)",
  },
  {
    id: 29,
    category: "FLORAL FLOWER POTS",
    name: "Flower Pot Special Super Deluxe",
    rate: 240,
    per: "Box (2 Pcs)",
  },
  {
    id: 30,
    category: "FLORAL FLOWER POTS",
    name: "Colour Koti",
    rate: 400,
    per: "Box (10 Pcs)",
  },
  {
    id: 31,
    category: "FLORAL FLOWER POTS",
    name: "Colour Koti Special",
    rate: 480,
    per: "Box (10 Pcs)",
  },
  {
    id: 32,
    category: "FLORAL FLOWER POTS",
    name: "Colour Koti - Mama Biskothu",
    rate: 600,
    per: "Box (10 Pcs)",
  },
  {
    id: 33,
    category: "FLORAL FLOWER POTS",
    name: "Pancharanga - Mothers",
    rate: 220,
    per: "Box (5 Pcs)",
  },
  {
    id: 34,
    category: "CHAK DE CHAKKARS",
    name: "Ground Chakkar Big",
    rate: 100,
    per: "Box (10 Pcs)",
  },
  {
    id: 35,
    category: "CHAK DE CHAKKARS",
    name: "Ground Chakkar Special",
    rate: 160,
    per: "Box (10 Pcs)",
  },
  {
    id: 36,
    category: "CHAK DE CHAKKARS",
    name: "Ground Chakkar Deluxe",
    rate: 280,
    per: "Box (10 Pcs)",
  },
  {
    id: 37,
    category: "CHAKKAR PREMIUM",
    name: "Wire Chakkar",
    rate: 320,
    per: "Box (10 Pcs)",
  },
  {
    id: 38,
    category: "CHAKKAR PREMIUM",
    name: "Ring Ring Flora - 4 x 4 Wheel",
    rate: 400,
    per: "Box (5 Pcs)",
  },
  {
    id: 39,
    category: "CHAKKAR PREMIUM",
    name: "Whistling Wheel",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 40,
    category: "CHAKKAR PREMIUM",
    name: "Disco Wheel",
    rate: 100,
    per: "Box (5 Pcs)",
  },
  {
    id: 41,
    category: "ONE SOUND CRACKERS",
    name: "2.75'' Kuruvi",
    rate: 24,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 42,
    category: "ONE SOUND CRACKERS",
    name: "3.5'' Lakshmi",
    rate: 40,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 43,
    category: "ONE SOUND CRACKERS",
    name: "4'' Lakshmi",
    rate: 60,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 44,
    category: "ONE SOUND CRACKERS",
    name: "4'' Lakshmi Super Deluxe",
    rate: 90,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 45,
    category: "ONE SOUND CRACKERS",
    name: "5'' Mega Deluxe",
    rate: 100,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 46,
    category: "ONE SOUND CRACKERS",
    name: "6'' Mega Deluxe",
    rate: 120,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 47,
    category: "ONE SOUND CRACKERS",
    name: "Gold Lakshmi",
    rate: 80,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 48,
    category: "ONE SOUND CRACKERS",
    name: "2 Sound Crackers",
    rate: 100,
    per: "Pkt (5 Pcs)",
  },
  {
    id: 49,
    category: "HOT BIJILI PACKS",
    name: "Red Bijili",
    rate: 80,
    per: "Bag (100 Pcs)",
  },
  {
    id: 50,
    category: "REPEATING BIJILIS",
    name: "Shin Chan (5 in 1) - 28 Chorsa",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 51,
    category: "REPEATING BIJILIS",
    name: "90 Watts Crackling - Digital",
    rate: 240,
    per: "Box (3 Pcs)",
  },
  {
    id: 52,
    category: "REPEATING BIJILIS",
    name: "100 Watts Crackling",
    rate: 90,
    per: "Box (1 Pcs)",
  },
  {
    id: 53,
    category: "REPEATING BIJILIS",
    name: "1000 Watts Crackling",
    rate: 400,
    per: "Box (1 Pcs)",
  },
  {
    id: 54,
    category: "REPEATING BIJILIS",
    name: "2000 Watts Crackling",
    rate: 800,
    per: "Box (1 Pcs)",
  },
  {
    id: 55,
    category: "REPEATING BIJILIS",
    name: "5000 Watts Crackling",
    rate: 2200,
    per: "Box (1 Pcs)",
  },
  {
    id: 56,
    category: "REPEATING BIJILIS",
    name: "10000 Watts Crackling",
    rate: 4400,
    per: "Box (1 Pcs)",
  },
  {
    id: 57,
    category: "REPEATING BIJILIS",
    name: "Magic Whip - 2000 Digital",
    rate: 350,
    per: "Box (1 Pcs)",
  },
  {
    id: 58,
    category: "MAJA SOUND PARTY",
    name: "Bullet Tera Bomb",
    rate: 80,
    per: "Box (10 Pcs)",
  },
  {
    id: 59,
    category: "MAJA SOUND PARTY",
    name: "Hydro Power Bomb",
    rate: 150,
    per: "Box (10 Pcs)",
  },
  {
    id: 60,
    category: "MAJA SOUND PARTY",
    name: "King of King Bomb",
    rate: 200,
    per: "Box (10 Pcs)",
  },
  {
    id: 61,
    category: "MAJA SOUND PARTY",
    name: "Classic Bomb / Tracer Bomb",
    rate: 260,
    per: "Box (10 Pcs)",
  },
  {
    id: 62,
    category: "MAJA SOUND PARTY",
    name: "Dinousar Deluxe Bomb",
    rate: 350,
    per: "Box (10 Pcs)",
  },
  {
    id: 63,
    category: "MAJA SOUND PARTY",
    name: "Digital Master Bomb - Jallikattu",
    rate: 450,
    per: "Box (10 Pcs)",
  },
  {
    id: 64,
    category: "PAPER BOMB",
    name: "1/4 Kg Paper Bomb - Jumbo",
    rate: 120,
    per: "Box (1 Pcs)",
  },
  {
    id: 65,
    category: "PAPER BOMB",
    name: "1/2 Kg Paper Bomb - Mega",
    rate: 240,
    per: "Box (1 Pcs)",
  },
  {
    id: 66,
    category: "PAPER BOMB",
    name: "1 Kg Paper Bomb - Bada",
    rate: 480,
    per: "Box (1 Pcs)",
  },
  {
    id: 67,
    category: "PAPER BOMB",
    name: "Money in Bank",
    rate: 120,
    per: "Box (1 Pcs)",
  },
  {
    id: 68,
    category: "PAPER BOMB",
    name: "Paper Bomb Veeran 1.0",
    rate: 600,
    per: "Box (10 Pcs)",
  },
  {
    id: 69,
    category: "PAPER BOMB",
    name: "Paper Bomb Veeran 2.0",
    rate: 800,
    per: "Box (10 Pcs)",
  },
  {
    id: 70,
    category: "ISRO LAUNCHERS",
    name: "Rocket Bomb",
    rate: 150,
    per: "Box (10 Pcs)",
  },
  {
    id: 71,
    category: "ISRO LAUNCHERS",
    name: "Lunik Express",
    rate: 300,
    per: "Box (10 Pcs)",
  },
  {
    id: 72,
    category: "ISRO LAUNCHERS",
    name: "Whistling Rocket",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 73,
    category: "PEACOCK DANCES",
    name: "Magical Peacock - 5 Face",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 74,
    category: "PEACOCK DANCES",
    name: "Peacock Special - Tri - Colours",
    rate: 400,
    per: "Box (1 Pcs)",
  },
  {
    id: 75,
    category: "PEACOCK DANCES",
    name: "Bada Peacock - 5 Face",
    rate: 900,
    per: "Box (1 Pcs)",
  },
  {
    id: 76,
    category: "PEACOCK DANCES",
    name: "Peacock Feathers",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 77,
    category: "PEACOCK DANCES",
    name: "Robo Dance - 7 Mines",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 78,
    category: "COLOUR FLASH",
    name: "Colour Changing Butterfly - 10 Pcs",
    rate: 200,
    per: "Box (10 Pcs)",
  },
  {
    id: 79,
    category: "COLOUR FLASH",
    name: "Helipter - Fly in the SKY",
    rate: 200,
    per: "Box (10 Pcs)",
  },
  {
    id: 80,
    category: "COLOUR FLASH",
    name: "Drone Nights",
    rate: 300,
    per: "Box (10 Pcs)",
  },
  {
    id: 81,
    category: "COLOUR FLASH",
    name: "Bambaram - Speed Max",
    rate: 220,
    per: "Box (10 Pcs)",
  },
  {
    id: 82,
    category: "COLOUR FLASH",
    name: "Photo Flash- Insta Flash",
    rate: 120,
    per: "Box (5 Pcs)",
  },
  {
    id: 83,
    category: "COLOUR FLASH",
    name: "Rainbow Colour Smoke - 3 Pcs",
    rate: 400,
    per: "Box (5 Pcs)",
  },
  {
    id: 84,
    category: "COLOUR FOUNTAIN",
    name: "Moon Light",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 85,
    category: "COLOUR FOUNTAIN",
    name: "Star Light",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 86,
    category: "COLOUR FOUNTAIN",
    name: "Sun Light",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 87,
    category: "COLOUR FOUNTAIN",
    name: "Ice Cream Fountain - TIN",
    rate: 200,
    per: "Box (1 Pcs)",
  },
  {
    id: 88,
    category: "COLOUR FOUNTAIN",
    name: "Little Pops - GOLD",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 89,
    category: "COLOUR FOUNTAIN",
    name: "Wonder Pops - TITANIUM",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 90,
    category: "COLOUR FOUNTAIN",
    name: "Ashrafi Pops - Silver",
    rate: 180,
    per: "Box (5 Pcs)",
  },
  {
    id: 91,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "Mega Coconut Crackling Deluxe",
    rate: 700,
    per: "Box (3 Pcs)",
  },
  {
    id: 92,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "King Star Crackling",
    rate: 500,
    per: "Box (3 Pcs)",
  },
  {
    id: 93,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "Autumn Rain - 6'' Special",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 94,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "Winter Rain - 6'' Special",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 95,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "Water Queen - 6'' Cold Pyro",
    rate: 400,
    per: "Box (1 Pcs)",
  },
  {
    id: 96,
    category: "PREMIUM CRACKLING FOUNTAIN",
    name: "Magical Siren - Sound Party",
    rate: 340,
    per: "Box (3 Pcs)",
  },
  {
    id: 97,
    category: "KIDS MAGICAL TEAM",
    name: "Golden Flower",
    rate: 160,
    per: "Box (10 Pcs)",
  },
  {
    id: 98,
    category: "KIDS MAGICAL TEAM",
    name: "Kit Kat / Chit Put",
    rate: 80,
    per: "Box (10 Pcs)",
  },
  {
    id: 99,
    category: "KIDS MAGICAL TEAM",
    name: "Electric Stone",
    rate: 20,
    per: "Box (10 Pcs)",
  },
  {
    id: 100,
    category: "KIDS MAGICAL TEAM",
    name: "Magic Pops",
    rate: 20,
    per: "Box (10 Pcs)",
  },
  {
    id: 101,
    category: "KIDS MAGICAL TEAM",
    name: "Selfie Stick",
    rate: 100,
    per: "Box (3 Pcs)",
  },
  {
    id: 102,
    category: "KIDS MAGICAL TEAM",
    name: "Fire Egg",
    rate: 320,
    per: "Box (2 Pcs)",
  },
  {
    id: 103,
    category: "KIDS MAGICAL TEAM",
    name: "Snake Tablets",
    rate: 100,
    per: "Box (10 Pcs)",
  },
  {
    id: 104,
    category: "KIDS MAGICAL TEAM",
    name: "Lolly Pop - 60 Seconds Crackling",
    rate: 500,
    per: "Box (5 Pcs)",
  },
  {
    id: 105,
    category: "KIDS MAGICAL TEAM",
    name: "Cartoon",
    rate: 50,
    per: "Box (5 Pcs)",
  },
  {
    id: 106,
    category: "KIDS MAGICAL TEAM",
    name: "Zee Boom Baa",
    rate: 20,
    per: "Box (10 Pcs)",
  },
  {
    id: 107,
    category: "MATCH BOXES",
    name: "Classic 5 in 1 Match Box - Big",
    rate: 220,
    per: "Box (10 Pcs)",
  },
  {
    id: 108,
    category: "MATCH BOXES",
    name: "Classic 6 in 1 Match Box - Mega",
    rate: 200,
    per: "Box (6 Pcs)",
  },
  {
    id: 109,
    category: "MATCH BOXES",
    name: "Classic 10 in 1 Match Box - Bada",
    rate: 600,
    per: "Box (10 Pcs)",
  },
  {
    id: 110,
    category: "CHOTTA FANCY",
    name: "Fighter Knights",
    rate: 100,
    per: "Box (1 Pcs)",
  },
  {
    id: 111,
    category: "CHOTTA FANCY",
    name: "King of All Stars",
    rate: 100,
    per: "Box (1 Pcs)",
  },
  {
    id: 112,
    category: "CHOTTA FANCY",
    name: "Happy Island",
    rate: 100,
    per: "Box (1 Pcs)",
  },
  {
    id: 113,
    category: "CHOTTA FANCY",
    name: "Red Hots",
    rate: 100,
    per: "Box (1 Pcs)",
  },
  {
    id: 114,
    category: "CHOTTA FANCY",
    name: "Thunder Shower",
    rate: 100,
    per: "Box (1 Pcs)",
  },
  {
    id: 115,
    category: "CHOTTA FANCY",
    name: "Robo Dance",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 116,
    category: "CHOTTA FANCY",
    name: "Sky Shot Crackling",
    rate: 60,
    per: "Box (1 Pcs)",
  },
  {
    id: 117,
    category: "CHOTTA FANCY",
    name: "Hero Series (2 in 1)",
    rate: 100,
    per: "Box (2 Pcs)",
  },
  {
    id: 118,
    category: "SKY WONDERS - SHINGLE SHOTS",
    name: "2'' Fancy Pipes (4 Varieties)",
    rate: 200,
    per: "Box (1 Pcs)",
  },
  {
    id: 119,
    category: "SKY WONDERS - SHINGLE SHOTS",
    name: "2.5'' Fancy Pipes (4 Varieties)",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 120,
    category: "SKY WONDERS - SHINGLE SHOTS",
    name: "2.5'' Triple Ball - 3 Steps",
    rate: 400,
    per: "Box (1 Pcs)",
  },
  {
    id: 121,
    category: "SKY WONDERS - SHINGLE SHOTS",
    name: "2'' - 3 Piece Fancy Pipes (4 Variety)",
    rate: 600,
    per: "Box (1 Pcs)",
  },
  {
    id: 122,
    category: "3.5'' FANCY SPECIAL SKY WONDERS",
    name: "3.5'' Fancy Pipe (4 Variety)",
    rate: 550,
    per: "Box (1 Pcs)",
  },
  {
    id: 123,
    category: "3.5'' FANCY SPECIAL SKY WONDERS",
    name: "3.5'' Pink Pearls Special",
    rate: 600,
    per: "Box (1 Pcs)",
  },
  {
    id: 124,
    category: "3.5'' FANCY SPECIAL SKY WONDERS",
    name: "3.5'' Nayagara Special",
    rate: 650,
    per: "Box (1 Pcs)",
  },
  {
    id: 125,
    category: "3.5'' FANCY SPECIAL SKY WONDERS",
    name: "3.5'' Colour Punch (Double Pack)",
    rate: 1300,
    per: "Box (2 Pcs)",
  },
  {
    id: 126,
    category: "3.5'' FANCY SPECIAL SKY WONDERS",
    name: "3.5'' City Jumper - 7 Ball (Double Pack)",
    rate: 1400,
    per: "Box (2 Pcs)",
  },
  {
    id: 127,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Fancy Pipe",
    rate: 800,
    per: "Box (1 Pcs)",
  },
  {
    id: 128,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Double Ball - Double Dhamaka",
    rate: 1000,
    per: "Box (1 Pcs)",
  },
  {
    id: 129,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Seven - 7 Steps",
    rate: 850,
    per: "Box (1 Pcs)",
  },
  {
    id: 130,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Twelve Balls - 12 Steps",
    rate: 900,
    per: "Box (1 Pcs)",
  },
  {
    id: 131,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Strom Series (Double Pack)",
    rate: 1750,
    per: "Box (2 Pcs)",
  },
  {
    id: 132,
    category: "GRAND SKY WONDERS - DOUBLE PIECE PACKING",
    name: "4'' Tower Series (Double Pack)",
    rate: 2000,
    per: "Box (2 Pcs)",
  },
  {
    id: 133,
    category: "UNIQUE PRIME SHOOTERS",
    name: "6'' Yellow Prime",
    rate: 1500,
    per: "Box (1 Pcs)",
  },
  {
    id: 134,
    category: "UNIQUE PRIME SHOOTERS",
    name: "6'' Red Prime",
    rate: 1500,
    per: "Box (1 Pcs)",
  },
  {
    id: 135,
    category: "UNIQUE PRIME SHOOTERS",
    name: "6'' Green Prime",
    rate: 1500,
    per: "Box (1 Pcs)",
  },
  {
    id: 136,
    category: "UNIQUE PRIME SHOOTERS",
    name: "6'' White Prime",
    rate: 1500,
    per: "Box (1 Pcs)",
  },
  {
    id: 137,
    category: "MULTI SKY THUNDERS - BUDGET",
    name: "30 Multi Colour Shot",
    rate: 800,
    per: "Box (1 Pcs)",
  },
  {
    id: 138,
    category: "MULTI SKY THUNDERS - BUDGET",
    name: "60 Multi Colour Shot",
    rate: 1600,
    per: "Box (1 Pcs)",
  },
  {
    id: 139,
    category: "MULTI SKY THUNDERS - BUDGET",
    name: "120 Multi Colour Shot",
    rate: 3000,
    per: "Box (1 Pcs)",
  },
  {
    id: 140,
    category: "MULTI SKY THUNDERS - BUDGET",
    name: "240,Multi Colour Shot",
    rate: 6000,
    per: "Box (1 Pcs)",
  },

  {
    id: 141,
    category: "MULTI SKY THUNDERS - BUDGET",
    name: "30 Shot Volcona - Peacock Dance",
    rate: 1200,
    per: "Box (1 Pcs)",
  },
  {
    id: 142,
    category: "PREMIUM THUNDERS",
    name: "7 Shot Colour",
    rate: 200,
    per: "Box (5 Pcs)",
  },
  {
    id: 143,
    category: "PREMIUM THUNDERS",
    name: "12 Shot Rider Crackling",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 144,
    category: "PREMIUM THUNDERS",
    name: "12 Multi Colour Shot",
    rate: 400,
    per: "Box (1 Pcs)",
  },
  {
    id: 145,
    category: "PREMIUM THUNDERS",
    name: "15 Multi Colour Shot",
    rate: 600,
    per: "Box (1 Pcs)",
  },
  {
    id: 146,
    category: "PREMIUM THUNDERS",
    name: "25 Shot Rider Crackling",
    rate: 500,
    per: "Box (1 Pcs)",
  },
  {
    id: 147,
    category: "PREMIUM THUNDERS",
    name: "30 Multi Colour Shot",
    rate: 950,
    per: "Box (1 Pcs)",
  },
  {
    id: 148,
    category: "PREMIUM THUNDERS",
    name: "60 Multi Colour Shot",
    rate: 2000,
    per: "Box (1 Pcs)",
  },
  {
    id: 149,
    category: "PREMIUM THUNDERS",
    name: "120 Multi Colour Shot",
    rate: 4400,
    per: "Box (1 Pcs)",
  },
  {
    id: 150,
    category: "PREMIUM THUNDERS",
    name: "240 Multi Colour Shot",
    rate: 8000,
    per: "Box (1 Pcs)",
  },
  {
    id: 151,
    category: "BEAUTIFUL SKY CARE",
    name: "Grand Opening - 5 * 10 Multi Colour",
    rate: 5000,
    per: "Box (1 Pcs)",
  },
  {
    id: 152,
    category: "OTHERS",
    name: "Roll Cap",
    rate: 10,
    per: "Box (1 Pcs)",
  },
  { id: 153, category: "OTHERS", name: "Gun", rate: 30, per: "Box (1 Pcs)" },
  {
    id: 154,
    category: "OTHERS",
    name: "Tri Colour Fountain",
    rate: 300,
    per: "Box (3 Pcs)",
  },
  { id: 155, category: "GIFT BOX", name: "21 Items", rate: 350, per: "Box" },
  { id: 156, category: "GIFT BOX", name: "27 Items", rate: 550, per: "Box" },
  { id: 157, category: "GIFT BOX", name: "35 Items", rate: 850, per: "Box" },
  { id: 158, category: "GIFT BOX", name: "45 Items", rate: 1050, per: "Box" },
  { id: 159, category: "GIFT BOX", name: "50 Items", rate: 1000, per: "Box" },
  {
    id: 160,
    category: "NEW ITEMS",
    name: "Lemon Tree Ayyan",
    rate: 300,
    per: "Box (1 Pcs)",
  },
  {
    id: 161,
    category: "NEW ITEMS",
    name: "Navarang Pencil (Sri Vijay)",
    rate: 300,
    per: "Box (5 Pcs)",
  },
  {
    id: 162,
    category: "NEW ITEMS",
    name: "4'' Nayagara Series",
    rate: 900,
    per: "Box (1 Pcs)",
  },
];
